[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "saran612", email = "freelancexsaran@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "deep-translator>=1.11.4",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "instaloader>=4.15.3",
    "langdetect>=1.0.9",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.1",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
